version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/restaurantdb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpassword
    networks:
      - restaurant-network
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=restaurantdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    networks:
      - restaurant-network

networks:
  restaurant-network:
